// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gngvimtzuksotituzugv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduZ3ZpbXR6dWtzb3RpdHV6dWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNTg4MzksImV4cCI6MjA2MDgzNDgzOX0.GChTxPMJwH41swqIBDhUpvRAnW1ezqzUbIbN_cvOyZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);